# Queries

# Get All Posts
query GetAllPosts {
  posts {
    id
    title
    content
    published
    createdAt
  }
}

# Mutations

# Mutation - Create Post

mutation CreatePost {
  postCreate(post: {
    title: "Java is so verbose language.",
    content: "I have to admit that it is."
  }) {
    userErrors {
      message
    }
    post {
      title
      content
    }
  }
}

# Mutation - Update Post

mutation UpdatePost {
  postUpdate(postId: 3, post: {
    title: "The Best GraphQL course ever!"
  }) {
    userErrors {
      message
    }
    post {
      content
      title
    }
  }
}

# Mutation - Delete Post
mutation DeletePost {
  postDelete(postId: 5) {
    userErrors {
      message
    }
    post {
      title
      content
    }
  }
}