# Get Products (name, image)
query Product {
  products {
    name
    image
  }
}

# Get Product by Id
query GetProductById {
  product(id: "c2af9adc-d0b8-4d44-871f-cef66f86f7f6") {
    name
    description
    price
    image
  }
}

# Get Product Review by Id

query GetProductReviewById {
  product(id:
  "53a0724c-a416-4cac-ae45-bfaedce1f147"
  ){
    name
    description
    image
    price
    reviews {
      title
      comment
      rating
    }
  }
}

# Get Product onSale = true

query GetProductOnSale {
  products(filter: {
    onSale: true
  }) {
    name
    price
    onSale
  }
}

# Get Category Product by Id with onSale = true

query GetProductOnSale {
  category(id: "d914aec0-25b2-4103-9ed8-225d39018d1d") {
    name
    products(filter: {
      onSale: true
    }) {
      name
      onSale
    }
  }
}

# Get - Filtiring Product Rating
query FiltringProductRating {
  products(filter: {
    onSale: true,
    avgRating: 3
  }) {
    name
    price
    reviews {
      rating
    }
  }
}
# Mutation - Create a New Category

mutation {
  addCategory(input: {
    name: "Office"
  }) {
    id
    name
  }
}

# Mutation - Create a New Product

mutation addProduct {
  addProduct(input: {
    name: "Fork",
    image: "img-55",
    price: 799.99
    onSale: true,
    quantity: 3,
    categoryId: "c01b1ff4-f894-4ef2-b27a-22aacc2fca70",
    description: "The best Fork you ever seen!"
  }) {
    name
    id
  }
}

# Mutation - Create a new Review

mutation addReview {
  addReview(input: {
    date: "2022-31-03",
    title: "The Best Fork Ever!",
    comment: "I bought an excellent fork here. Highly recommend to everyone!",
    rating: 5,
    productId: "f2a2915d-1f91-46d4-8331-6eeaf73d2a2f"
  }) {
    title
    comment
    rating
  }
}